
# Data and charts will be placed in output/physiology/{name}/
# Data file will always be output/physiology/{name}/{name}.csv
name: liver_metabolism

# Name of the model file
model: Jerby2010_Liver_Metabolism.xml

# Which differential equation solver to use.
# Options are: adams_bashforth, adams_moulton, dormand_prince_54, dormand_prince_853, euler, gragg_bulirsh_stoer, higham_hall_54, rosenbrock, runge_kutta
solver: dormand_prince_853

# Simulation step size in seconds. Note that this can have significant effects on the results and may impact the ability of the solver to complete successfully.
stepSize: 0.01

# Simulation duration in seconds
duration: 60

## Model parameter inputs. Any unspecified parameters will use the model's default value.
#inputs:
#    hrmean: 80
#    arr_t0: 0.25
#    arr_t1: 0.35
#    arr_base: 0.2
#    rng_seed: 0.54345
#    #e_variance: 0.3
#    #vfib_start: 5
#    #vfib_end: 10

# What charts to draw. Results will be plotted on PNG images.
# Note that chart support is a convenience feature and many chart options cannot be manipulated here.
# If you need more control over the chart, import the csv file into another program with that capability.
charts:
    - filename: liver_metabolism.png
      type: line
      title: "liver_metabolism"
      axisParamX: time
      axisLabelX: time (?)
      axisLabelY: Metabolites
      #lowerBoundY: -0.05
      #upperBoundY: 0.15
      series:
        - param: M_ac_c
        - param: M_acetone_c
        - param: M_ach_c
        - param: M_ade_c
        - param: M_adrnl_c
        - param: M_bilirub_c
        - param: M_chsterol_c
        - param: M_co2_c
        - param: M_creat_e
        
        



#<listOfParameters>
#      <parameter metaid="_650898" id="LOWER_BOUND" value="0" units="mmol_per_gDW_per_hr"/>
#      <parameter metaid="_650899" id="UPPER_BOUND" value="1000" units="mmol_per_gDW_per_hr"/>
#      <parameter metaid="_650902" id="OBJECTIVE_COEFFICIENT" value="0"/>
#      <parameter metaid="_650905" id="FLUX_VALUE" value="500" units="mmol_per_hr"/>
#</listOfParameters>
