services:
  synthea:
    build:
      context: .
      args:
        SYNTHEA_VERSION: ${SYNTHEA_VERSION:-docker-compose}
    image: synthea-local
    environment:
      SYNTHEA_OUTPUT_DIR: ${SYNTHEA_OUTPUT_DIR:-/synthea-output}
      SYNTHEA_OUTPUT_FORMAT: ${SYNTHEA_OUTPUT_FORMAT:-fhir}
      SYNTHEA_POPULATION: ${SYNTHEA_POPULATION:-10}
      SYNTHEA_STATE: ${SYNTHEA_STATE:-Massachusetts}
      SYNTHEA_CITY: ${SYNTHEA_CITY:-}
      SYNTHEA_SEED: ${SYNTHEA_SEED:-}
      SYNTHEA_CLINICIAN_SEED: ${SYNTHEA_CLINICIAN_SEED:-}
      SYNTHEA_SINGLE_PERSON_SEED: ${SYNTHEA_SINGLE_PERSON_SEED:-}
      SYNTHEA_REFERENCE_DATE: ${SYNTHEA_REFERENCE_DATE:-}
      SYNTHEA_END_DATE: ${SYNTHEA_END_DATE:-}
      SYNTHEA_GENDER: ${SYNTHEA_GENDER:-}
      SYNTHEA_AGE_RANGE: ${SYNTHEA_AGE_RANGE:-}
      SYNTHEA_OVERFLOW: ${SYNTHEA_OVERFLOW:-}
      SYNTHEA_MODULES: ${SYNTHEA_MODULES:-}
      SYNTHEA_CONFIG_FILE: ${SYNTHEA_CONFIG_FILE:-}
      SYNTHEA_LOCAL_MODULES_DIR: ${SYNTHEA_LOCAL_MODULES_DIR:-}
      SYNTHEA_INITIAL_SNAPSHOT: ${SYNTHEA_INITIAL_SNAPSHOT:-}
      SYNTHEA_UPDATED_SNAPSHOT: ${SYNTHEA_UPDATED_SNAPSHOT:-}
      SYNTHEA_UPDATE_DAYS: ${SYNTHEA_UPDATE_DAYS:-}
      SYNTHEA_FIXED_RECORD_PATH: ${SYNTHEA_FIXED_RECORD_PATH:-}
      SYNTHEA_KEEP_PATIENTS_PATH: ${SYNTHEA_KEEP_PATIENTS_PATH:-}
    volumes:
      - ./output:${SYNTHEA_OUTPUT_DIR:-/synthea-output}
