### DO NOT MODIFY THIS FILE - IT WAS AUTOMATICALLY GENERATED BY RAKE TASK 'build_shr_mapping'
### GENERATED 2017-02-24 07:42:53 -0500
module Synthea
  SHR_MAPPING = {
    'http://ncimeta.nci.nih.gov' => {
      'C0001948' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-AlcoholUse"},
      'C0012155' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-DietAndNutrition"},
      'C0242566' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-IntravenousDrugUse"},
      'C0238646' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-AnimalExposure"},
      'C0557163' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-AnnualIncome"},
      'C0206073' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-DomesticViolence"},
      'C0000768' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-CongenitalAbnormalities"},
      'C0557162' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-IncomeSource"},
      'C1820459' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-IncomeStability"},
      'C0557509' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-environment-NumberOfDependents"},
      'C0871747' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-PrenatalExposure"},
      'C0040802' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-Travel"},
      'C0700589' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-sex-ContraceptiveMethodsUsed"},
    },
    'http://loinc.org' => {
      '11367-0' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-ONCSmokingStatus"},
      '28323-4' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-SleepQuality"},
      '81364-2' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-behavior-ReligiousPractice"},
      '63504-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-EducationalAttainment"},
      '74165-2' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-Employment"},
      '74287-4' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-lifehistory-Occupation"},
      '64631-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-sex-PregnancyIntention"},
      '54574-9' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-skin-PressureUlcerManifestation"},
      '55284-4' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BloodPressure"},
      '8302-2' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BodyHeight"},
      '8306-3' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BodyLength"},
      '39156-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BodyMassIndex"},
      '8310-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BodyTemperature"},
      '29463-7' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-BodyWeight"},
      '8462-4' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-DiastolicPressure"},
      '8287-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-HeadCircumference"},
      '8867-4' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-HeartRate"},
      '59408-5' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-OxygenSaturation"},
      '9279-1' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-RespiratoryRate"},
      '8480-6' => {:url=>"http://standardhealthrecord.org/fhir/StructureDefinition/shr-vital-SystolicPressure"},
    },
  }.freeze
end
