import org.mitre.synthea.modules.CommunityHealthWorker;
import org.mitre.synthea.modules.Generator;
import org.mitre.synthea.modules.Person;
//import org.mitre.synthea.modules.Module;
import org.mitre.synthea.modules.VitalSign;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
 
	public static void main(String[] args) throws Exception {
		Generator generator = new Generator(10);
		generator.run();

		System.out.format("Number of Towns: %d\n", CommunityHealthWorker.workers.size());
		System.out.format("Number of CHWs: %d\n", CommunityHealthWorker.budget / CommunityHealthWorker.cost);
	}
}
